# ArgoCD Application-specific values
argocd:
  appName: cf_vfa_edge
  env: oc_intg
  destinationNamespace: ws-b2b-intg-domain

# ConfigMap values
configmap:
  name: app-config-intg
  data:
    ENV: "accp"
    API_URL: "https://api.accp.example.com"

# Secret values
secret:
  name: app-secret-intg
  data:
    DB_PASSWORD: "supersecretpassword"
