apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        revision: "main"
        directories:
          - path: "*/*"  # ✅ Now detects {app_name}/{env_name}/ directly
  template:
    metadata:
      name: '{{path.basename}}'  # Uses env name (e.g., oc_unit)
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        path: "{{path}}"  # ✅ Uses {app_name}/{env_name}
        targetRevision: main
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{path[0]}}'  # ✅ App name becomes namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
