apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        revision: "release-test"
        directories:
          - path: "*/*"  # Detects all appX/oc_env directories
  template:
    metadata:
      name: reloader
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        path: "{{path}}"  # Uses {app_name}/{env_name}
        targetRevision: release-test
      destination:
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
