apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-reloader # This is the single ArgoCD app managing all sub-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/madhan-s1/stakator-configrepo.git" # Replace with your repo
    targetRevision: release-voya # Branch to track
    path: argoCD/base/oc_unit # This is where the base kustomization.yaml lives
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
