apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        revision: "main"
        directories:
          - path: "*/*"  # ✅ Detects {app_name}/{env_name}/ automatically
  template:
    metadata:
      name: reloader
    spec:
      project: default
      source:
        repoURL: "https://github.com/madhan-s1/stakator-configrepo.git"
        path: "charts"
        targetRevision: main
        helm:
          valueFiles:
            - {{path[0]}}/{{path[1]}}/values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{ .Values.argocd.destinationNamespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
